const { Command } = require('commander')
const program = new Command()
const { setConfig } = require('./config')
const upload = require('./events/uploadToFirestore')
const download = require('./events/downloadToLocal')
const getEventFormStatistics = require('./events/getEventFormStatistics')
const categoriseFeedbacks = require('./events/categoriseFeedbacksInFirestore')
const uploadGoogleReviews = require('./events/uploadGoogleReviewsToFirestore')
const processGoogleForms = require('./events/processGoogleForms')
const designateAsAdmin = require('./admins/designateAsAdmin')
const listAdminUsers = require('./admins/listAdminUsers')
const runMigration = require('./platform/migrations/runMigration')
const generateRandomAnswers = require('./events/generateRandomAnswers')

program.option('--prod', 'Run in production mode', false)

program.addCommand(upload)
program.addCommand(download)
program.addCommand(getEventFormStatistics)
program.addCommand(categoriseFeedbacks)
program.addCommand(uploadGoogleReviews)
program.addCommand(processGoogleForms)
program.addCommand(designateAsAdmin)
program.addCommand(listAdminUsers)
program.addCommand(runMigration)
program.addCommand(generateRandomAnswers)

program.hook('preAction', command => {
    console.log(`Running in ${command.opts().prod ? 'PROD' : 'LOCAL'} env`)
    setConfig('prod', command.opts().prod)
})

program.parse(process.argv)
